# Generated by Django 3.1 on 2020-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20201006_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2013-2-4'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default='2013-2-4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default='2013-2-4'),
        ),
    ]
