# Generated by Django 3.1 on 2022-08-22 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0006_auto_20220822_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Main.answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
